### ISSUE TITLE
能增加个视频，浏览器全屏功能吗

### ISSUE THREAD

**Issue by hh0318** [Youguang-Zhou/67373-website#1]
能增加个视频，浏览器全屏功能吗

**Comment by Youguang-Zhou** [comment]
谢谢你的建议！但是我最近有点忙，等过阵子空下来我会想办法实现的。

**Comment by hh0318** [comment]
辛苦了~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Youguang-Zhou/67373-website"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月24日(星期三) 凌晨5:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Youguang-Zhou/67373-website] 能增加个视频，浏览器全屏功能吗 (Issue #1)





 
谢谢你的建议！但是我最近有点忙，等过阵子空下来我会想办法实现的。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Youguang-Zhou** [comment]
完成啦，在播放器里新增了剧场模式按钮，点击即可浏览器全屏～
